In [2]:
import pandas as pd
#Đọc dữ liệu file merge
import pandas as pd

merge = pd.read_csv("data_clean/merge.csv")

In [9]:
# Tạo cột present_flag
# Tạo cột đánh dấu Có mặt
merge["present_flag"] = (merge["status"] == "Có mặt").astype(int)

pivot_attendance_rate = pd.pivot_table(
    merge,
    index=["student_id", "class_id"],
    values="present_flag",
    aggfunc="mean"
)

pivot_attendance_rate.rename(
    columns={"present_flag": "attendance_rate"},
    inplace=True
)

pivot_attendance_rate

                     attendance_rate
student_id class_id
Sv001      HP10101               1.0
Sv002      HP20502               0.0
Sv003      HP10101               0.0

In [10]:
absent_df = merge[merge["status"] == "Vắng"]

pivot_absent = pd.pivot_table(
    absent_df,
    index="course_name",
    columns="weekday",
    values="student_id",
    aggfunc="count",
    fill_value=0
)

pivot_absent

weekday           Monday
course_name
Lap Trinh Python       1
Lập Trình Py           1

In [11]:
pivot_cohort = pd.pivot_table(
    merge,
    index="class_id",
    columns="class_cohort",
    values="present_flag",
    aggfunc="mean"
)

pivot_cohort

class_cohort  k17a1  k18a2
class_id
HP10101         1.0    0.0
HP20502         0.0    NaN

In [13]:
stacked_absent = pivot_absent.stack().reset_index()
stacked_absent.columns = ["course_name", "weekday", "absent_count"]

In [14]:
unstacked_absent = stacked_absent.set_index(
    ["course_name", "weekday"]
).unstack()

unstacked_absent

                 absent_count
weekday                Monday
course_name
Lap Trinh Python            1
Lập Trình Py                1